//! `xtask check-profile-asset-catalog` — keep install profile asset index in sync.
//!
//! The install catalog embeds standards markdown via a generated Rust module.
//! This guard regenerates the canonical module text from the filesystem and
//! fails when the checked-in file drifts.

use anyhow::{Context, Result, bail};
use std::fmt::Write as _;
use std::fs;
use std::io::Write;
use std::path::Path;
use walkdir::WalkDir;

const PROFILE_ROOT_REPO_PATH: &str = "profiles/rust-cargo";
const GENERATED_INDEX_REPO_PATH: &str =
    "crates/tanren-cli-app/src/install/rust_cargo_profile_assets.rs";

pub(crate) fn run(root: &Path, write: bool) -> Result<()> {
    let markdown_paths = collect_markdown_paths(root)?;
    let expected = render_generated_module(&markdown_paths);
    let generated_path = root.join(GENERATED_INDEX_REPO_PATH);

    let current = if generated_path.exists() {
        Some(
            fs::read_to_string(&generated_path)
                .with_context(|| format!("read {}", generated_path.display()))?,
        )
    } else {
        None
    };

    if current.as_deref() == Some(expected.as_str()) {
        let stdout = std::io::stdout();
        let mut handle = stdout.lock();
        let _ = writeln!(
            handle,
            "check-profile-asset-catalog: 0 violations ({} markdown file(s) indexed)",
            markdown_paths.len()
        );
        return Ok(());
    }

    if write {
        fs::write(&generated_path, expected)
            .with_context(|| format!("write {}", generated_path.display()))?;
        let stdout = std::io::stdout();
        let mut handle = stdout.lock();
        let _ = writeln!(
            handle,
            "check-profile-asset-catalog: regenerated {GENERATED_INDEX_REPO_PATH} from {PROFILE_ROOT_REPO_PATH}"
        );
        return Ok(());
    }

    let stderr = std::io::stderr();
    let mut handle = stderr.lock();
    let _ = writeln!(
        handle,
        "{GENERATED_INDEX_REPO_PATH} is out of sync with {PROFILE_ROOT_REPO_PATH}"
    );
    let _ = writeln!(
        handle,
        "run: cargo run -p tanren-xtask -- check-profile-asset-catalog --write"
    );
    bail!("check-profile-asset-catalog: generated install profile asset index drift detected");
}

fn collect_markdown_paths(root: &Path) -> Result<Vec<String>> {
    let profile_root = root.join(PROFILE_ROOT_REPO_PATH);
    if !profile_root.exists() {
        bail!(
            "check-profile-asset-catalog: profile root '{}' does not exist",
            profile_root.display()
        );
    }

    let mut paths = Vec::new();
    for entry in WalkDir::new(&profile_root)
        .into_iter()
        .filter_map(Result::ok)
    {
        if !entry.file_type().is_file() {
            continue;
        }
        if entry.path().extension().is_none_or(|ext| ext != "md") {
            continue;
        }
        let rel = repo_relative(entry.path(), root)?;
        paths.push(rel);
    }

    paths.sort_unstable();
    if paths.is_empty() {
        bail!(
            "check-profile-asset-catalog: no markdown files found under {PROFILE_ROOT_REPO_PATH}"
        );
    }

    Ok(paths)
}

fn repo_relative(path: &Path, root: &Path) -> Result<String> {
    let relative = path
        .strip_prefix(root)
        .with_context(|| format!("strip '{}' prefix from {}", root.display(), path.display()))?;
    Ok(path_to_slash(relative))
}

fn path_to_slash(path: &Path) -> String {
    path.components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

fn render_generated_module(paths: &[String]) -> String {
    let mut out = String::new();
    out.push_str("//! Generated rust-cargo standards asset catalog.\n");
    out.push_str("//!\n");
    out.push_str(
        "//! This file is generated by `tanren-xtask check-profile-asset-catalog --write`.\n",
    );
    out.push_str("//! Do not edit by hand.\n\n");
    out.push_str("pub(super) const RUST_CARGO_PROFILE_SOURCES: &[(&str, &str)] = &[\n");

    for path in paths {
        out.push_str("    (\n");
        let _ = writeln!(out, "        \"{path}\",");
        out.push_str("        include_str!(concat!(\n");
        out.push_str("            env!(\"CARGO_MANIFEST_DIR\"),\n");
        let _ = writeln!(out, "            \"/../../{path}\"");
        out.push_str("        )),\n");
        out.push_str("    ),\n");
    }

    out.push_str("];\n");
    out
}
