#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
cd "${REPO_ROOT}"

usage() {
    cat <<'USAGE'
Usage: scripts/proof/phase0/verify.sh <pack_dir>

Validate a Phase 0 proof pack generated by scripts/proof/phase0/run.sh.
USAGE
}

if [[ $# -ne 1 ]]; then
    usage >&2
    exit 2
fi

PACK_DIR="$1"
if [[ ! -d "${PACK_DIR}" ]]; then
    echo "Pack dir not found: ${PACK_DIR}" >&2
    exit 2
fi

required_files=(
    "summary.json"
    "summary.md"
    "auth-replay/summary.json"
    "replay-pack/verdicts/equivalence.json"
    "replay-pack/verdicts/rollback.json"
    "manual-walkthrough/summary.json"
)

for rel in "${required_files[@]}"; do
    if [[ ! -f "${PACK_DIR}/${rel}" ]]; then
        echo "Missing required file: ${PACK_DIR}/${rel}" >&2
        exit 1
    fi
done

scenario_ids=(
    "1.1" "1.2"
    "2.1" "2.2" "2.3"
    "3.1" "3.2"
    "4.1" "4.2"
    "5.1" "5.2"
    "6.1" "6.2" "6.3"
    "7.1" "7.2" "7.3"
    "8.1"
)

for sid in "${scenario_ids[@]}"; do
    if [[ ! -f "${PACK_DIR}/scenarios/${sid}/positive/PASS" ]]; then
        echo "Missing positive PASS marker for scenario ${sid}" >&2
        exit 1
    fi
    if [[ ! -f "${PACK_DIR}/scenarios/${sid}/falsification/PASS" ]]; then
        echo "Missing falsification PASS marker for scenario ${sid}" >&2
        exit 1
    fi
done

uv run python - "${PACK_DIR}" <<'PY'
from __future__ import annotations

import json
from pathlib import Path

root = Path(__import__("sys").argv[1])
summary = json.loads((root / "summary.json").read_text(encoding="utf-8"))
if summary.get("status") != "pass":
    raise SystemExit("summary.json status is not pass")

scenarios = summary.get("scenarios", [])
if len(scenarios) != 18:
    raise SystemExit(f"expected 18 scenarios, found {len(scenarios)}")

for row in scenarios:
    if row.get("status") != "pass":
        raise SystemExit(f"scenario {row.get('scenario')} status is not pass")
    for witness_kind in ("positive", "falsification"):
        witness = row.get(witness_kind)
        if not witness:
            raise SystemExit(f"scenario {row.get('scenario')} missing {witness_kind} witness")
        if witness.get("status") != "pass":
            raise SystemExit(
                f"scenario {row.get('scenario')} {witness_kind} witness did not pass"
            )

supplemental_checks = {
    "auth-replay/summary.json": ["status", "pass"],
    "replay-pack/verdicts/equivalence.json": ["status", "pass"],
    "replay-pack/verdicts/rollback.json": ["status", "pass"],
    "manual-walkthrough/summary.json": ["status", "pass"],
}

for rel, (field, expected) in supplemental_checks.items():
    data = json.loads((root / rel).read_text(encoding="utf-8"))
    if data.get(field) != expected:
        raise SystemExit(f"{rel} expected {field}={expected}, found {data.get(field)!r}")
PY

echo "Phase 0 proof pack verification passed: ${PACK_DIR}"
