//! Generate web deployment-posture contract artifacts from canonical
//! Rust/OpenAPI sources.
//!
//! The web surface consumes API-backed contract shapes. To avoid drift,
//! this generator derives:
//! - TypeScript posture contract types from the API `OpenAPI` schema.
//! - Supported-posture fixture summaries from `tanren-contract` posture
//!   enums + capability-summary logic.

use anyhow::{Context, Result, bail};
use serde_json::Value;
use std::collections::BTreeMap;
use std::fs;
use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};
use tanren_contract::{
    DeploymentPosture, DeploymentPostureCapabilitySummary, SupportedDeploymentPosture,
    SupportedDeploymentPosturesResponse,
};

const GENERATED_DIR_REL: &str = "apps/web/src/app/lib/generated";
const CONTRACT_FILE: &str = "deployment-posture-contract.ts";
const FIXTURES_FILE: &str = "deployment-posture-fixtures.ts";

pub(crate) fn run(root: &Path, check: bool) -> Result<()> {
    let openapi = tanren_api_app::openapi_document();
    let openapi_json = serde_json::to_value(&openapi).context("serialize OpenAPI document")?;
    let schemas = openapi_json
        .pointer("/components/schemas")
        .and_then(Value::as_object)
        .context("OpenAPI document missing components.schemas")?;

    let contract = format_typescript(
        root,
        &format!("{GENERATED_DIR_REL}/{CONTRACT_FILE}"),
        &render_contract_ts(schemas)?,
    )?;
    let fixtures = format_typescript(
        root,
        &format!("{GENERATED_DIR_REL}/{FIXTURES_FILE}"),
        &render_fixtures_ts()?,
    )?;

    let generated_dir = root.join(GENERATED_DIR_REL);
    let contract_path = generated_dir.join(CONTRACT_FILE);
    let fixtures_path = generated_dir.join(FIXTURES_FILE);

    if check {
        verify_file_is_current(&contract_path, &contract)?;
        verify_file_is_current(&fixtures_path, &fixtures)?;
        return Ok(());
    }

    fs::create_dir_all(&generated_dir)
        .with_context(|| format!("create {}", generated_dir.display()))?;
    fs::write(&contract_path, contract)
        .with_context(|| format!("write {}", contract_path.display()))?;
    fs::write(&fixtures_path, fixtures)
        .with_context(|| format!("write {}", fixtures_path.display()))?;

    Ok(())
}

fn verify_file_is_current(path: &Path, expected: &str) -> Result<()> {
    let actual = fs::read_to_string(path)
        .with_context(|| format!("read generated artifact {}", path.display()))?;
    if actual == expected {
        return Ok(());
    }
    bail!(
        "generated artifact drift: {} is stale; run `cargo run -q -p tanren-xtask -- generate-web-posture-contract`",
        path.display()
    )
}

fn render_contract_ts(schemas: &serde_json::Map<String, Value>) -> Result<String> {
    let mut out = String::new();
    out.push_str(
        r"/**
 * Generated by `tanren-xtask generate-web-posture-contract`.
 *
 * OpenAPI source: `crates/tanren-api-app/src/routes.rs` (`ApiDoc`).
 * Contract source: `crates/tanren-contract/src/deployment_posture.rs`.
 * DO NOT EDIT MANUALLY.
 */

",
    );

    let deployment_posture = schema_to_ts(type_schema(schemas, "DeploymentPosture")?)?;
    emit_alias(&mut out, "DeploymentPosture", &deployment_posture);
    let failure_codes = schema_to_ts(type_schema(schemas, "DeploymentPostureFailureReason")?)?;
    emit_alias(&mut out, "DeploymentPostureFailureCode", &failure_codes);
    let capabilities = schema_to_ts(type_schema(schemas, "DeploymentPostureCapability")?)?;
    emit_alias(&mut out, "DeploymentPostureCapability", &capabilities);
    let unavailable_reasons = schema_to_ts(type_schema(
        schemas,
        "DeploymentPostureCapabilityUnavailableReason",
    )?)?;
    emit_alias(
        &mut out,
        "DeploymentPostureCapabilityUnavailableReason",
        &unavailable_reasons,
    );
    emit_interface(
        &mut out,
        "DeploymentPostureUnavailableCapability",
        object_fields(
            Some("DeploymentPostureUnavailableCapability"),
            type_schema(schemas, "DeploymentPostureUnavailableCapability")?,
        )?,
    );
    emit_interface(
        &mut out,
        "DeploymentPostureCapabilitySummary",
        object_fields(
            Some("DeploymentPostureCapabilitySummary"),
            type_schema(schemas, "DeploymentPostureCapabilitySummary")?,
        )?,
    );
    let scope = schema_to_ts(type_schema(schemas, "DeploymentPostureScope")?)?;
    emit_alias(&mut out, "DeploymentPostureScope", &scope);
    emit_interface(
        &mut out,
        "SetDeploymentPostureRequest",
        object_fields(
            Some("SetDeploymentPostureRequest"),
            type_schema(schemas, "SetDeploymentPostureRequest")?,
        )?,
    );
    emit_interface(
        &mut out,
        "SetDeploymentPostureResponse",
        object_fields(
            Some("SetDeploymentPostureResponse"),
            type_schema(schemas, "SetDeploymentPostureResponse")?,
        )?,
    );
    emit_interface(
        &mut out,
        "SupportedDeploymentPosture",
        object_fields(
            Some("SupportedDeploymentPosture"),
            type_schema(schemas, "SupportedDeploymentPosture")?,
        )?,
    );
    emit_interface(
        &mut out,
        "SupportedDeploymentPosturesResponse",
        object_fields(
            Some("SupportedDeploymentPosturesResponse"),
            type_schema(schemas, "SupportedDeploymentPosturesResponse")?,
        )?,
    );
    emit_interface(
        &mut out,
        "DeploymentPostureReadModel",
        object_fields(
            Some("DeploymentPostureReadModel"),
            type_schema(schemas, "DeploymentPostureReadModel")?,
        )?,
    );
    emit_interface(
        &mut out,
        "CurrentDeploymentPostureResponse",
        object_fields(
            Some("CurrentDeploymentPostureResponse"),
            type_schema(schemas, "CurrentDeploymentPostureResponse")?,
        )?,
    );

    Ok(out)
}

fn render_fixtures_ts() -> Result<String> {
    let mut out = String::new();
    out.push_str(
        "/**\n\
         * Generated by `tanren-xtask generate-web-posture-contract`.\n\
         *\n\
         * Contract source: `crates/tanren-contract/src/deployment_posture.rs`.\n\
         * DO NOT EDIT MANUALLY.\n\
         */\n\
         \n\
         import type {\n\
           DeploymentPosture,\n\
           DeploymentPostureCapabilitySummary,\n\
         } from \"./deployment-posture-contract\";\n\
         \n",
    );

    let supported: Vec<&'static str> = DeploymentPosture::ALL
        .iter()
        .copied()
        .map(DeploymentPosture::as_wire_value)
        .collect();
    out.push_str("export const SUPPORTED_DEPLOYMENT_POSTURES: readonly DeploymentPosture[] = ");
    out.push_str(&to_ts_json(&supported)?);
    out.push_str(";\n\n");

    let supported_response = SupportedDeploymentPosturesResponse {
        supported: DeploymentPosture::ALL
            .iter()
            .copied()
            .map(|posture| SupportedDeploymentPosture {
                posture,
                capability_summary: DeploymentPostureCapabilitySummary::for_posture(posture),
            })
            .collect(),
    };
    let summary_by_posture: BTreeMap<String, DeploymentPostureCapabilitySummary> =
        supported_response
            .supported
            .into_iter()
            .map(|entry| {
                (
                    entry.posture.as_wire_value().to_owned(),
                    entry.capability_summary,
                )
            })
            .collect();

    out.push_str(
        "const CAPABILITY_SUMMARY_BY_POSTURE: Record<\n  DeploymentPosture,\n  DeploymentPostureCapabilitySummary\n> = ",
    );
    out.push_str(&to_ts_json(&summary_by_posture)?);
    out.push_str(";\n\n");

    out.push_str(
        "export function capabilitySummaryForPosture(\n  posture: DeploymentPosture,\n): DeploymentPostureCapabilitySummary {\n  return CAPABILITY_SUMMARY_BY_POSTURE[posture];\n}\n",
    );

    Ok(out)
}

fn type_schema<'a>(schemas: &'a serde_json::Map<String, Value>, name: &str) -> Result<&'a Value> {
    schemas
        .get(name)
        .with_context(|| format!("OpenAPI schema `{name}` missing"))
}

fn object_fields(schema_name: Option<&str>, schema: &Value) -> Result<Vec<(String, bool, String)>> {
    let required = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(Value::as_str)
                .map(str::to_owned)
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();

    let props = schema
        .get("properties")
        .and_then(Value::as_object)
        .context("object schema missing `properties`")?;

    let mut fields = Vec::with_capacity(props.len());
    for (name, child) in props {
        let ty = schema_to_ts(child)?;
        let is_required =
            required.iter().any(|item| item == name) || forced_required(schema_name, name);
        fields.push((name.clone(), is_required, ty));
    }
    Ok(fields)
}

fn forced_required(schema_name: Option<&str>, field_name: &str) -> bool {
    matches!(
        (schema_name, field_name),
        (Some("CurrentDeploymentPostureResponse"), "current")
    )
}

fn emit_alias(out: &mut String, name: &str, value: &str) {
    out.push_str("export type ");
    out.push_str(name);
    out.push_str(" = ");
    out.push_str(value);
    out.push_str(";\n\n");
}

fn emit_interface(out: &mut String, name: &str, fields: Vec<(String, bool, String)>) {
    out.push_str("export interface ");
    out.push_str(name);
    out.push_str(" {\n");
    for (field_name, required, ty) in fields {
        out.push_str("  ");
        out.push_str(&field_name);
        if !required {
            out.push('?');
        }
        out.push_str(": ");
        out.push_str(&ty);
        out.push_str(";\n");
    }
    out.push_str("}\n\n");
}

fn schema_to_ts(schema: &Value) -> Result<String> {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        let name = reference
            .split('/')
            .next_back()
            .context("invalid $ref")?
            .to_owned();
        if matches!(name.as_str(), "AccountId" | "ProjectId" | "InstallationId") {
            return Ok("string".to_owned());
        }
        return Ok(name);
    }

    let mut base = if let Some(one_of) = schema.get("oneOf").and_then(Value::as_array) {
        union_types(one_of)?
    } else if let Some(any_of) = schema.get("anyOf").and_then(Value::as_array) {
        union_types(any_of)?
    } else if let Some(enum_values) = schema.get("enum").and_then(Value::as_array) {
        enum_union(enum_values)?
    } else {
        match schema.get("type").and_then(Value::as_str) {
            Some("string") => "string".to_owned(),
            Some("integer" | "number") => "number".to_owned(),
            Some("boolean") => "boolean".to_owned(),
            Some("null") => "null".to_owned(),
            Some("array") => {
                let items = schema
                    .get("items")
                    .context("array schema missing `items`")?;
                let item_type = schema_to_ts(items)?;
                format!("{item_type}[]")
            }
            Some("object") => inline_object(schema)?,
            Some(other) => bail!("unsupported schema type `{other}`"),
            None => {
                if schema.get("properties").is_some() {
                    inline_object(schema)?
                } else {
                    bail!("unsupported schema shape: {schema}")
                }
            }
        }
    };

    if schema
        .get("nullable")
        .and_then(Value::as_bool)
        .unwrap_or(false)
    {
        base = format!("{base} | null");
    }

    Ok(base)
}

fn union_types(items: &[Value]) -> Result<String> {
    let mut rendered = Vec::with_capacity(items.len());
    for item in items {
        rendered.push(schema_to_ts(item)?);
    }
    Ok(rendered.join(" | "))
}

fn enum_union(items: &[Value]) -> Result<String> {
    let mut rendered = Vec::with_capacity(items.len());
    for item in items {
        let value = item
            .as_str()
            .with_context(|| format!("non-string enum value: {item}"))?;
        rendered.push(format!("\"{value}\""));
    }
    Ok(rendered.join(" | "))
}

fn inline_object(schema: &Value) -> Result<String> {
    let fields = object_fields(None, schema)?;
    let mut out = String::new();
    out.push_str("{ ");
    for (idx, (name, required, ty)) in fields.into_iter().enumerate() {
        if idx > 0 {
            out.push(' ');
        }
        out.push_str(&name);
        if !required {
            out.push('?');
        }
        out.push_str(": ");
        out.push_str(&ty);
        out.push(';');
    }
    out.push_str(" }");
    Ok(out)
}

fn to_ts_json<T: serde::Serialize>(value: &T) -> Result<String> {
    serde_json::to_string_pretty(value).context("serialize generated JSON literal")
}

fn format_typescript(root: &Path, virtual_path: &str, content: &str) -> Result<String> {
    let mut child = Command::new("pnpm")
        .current_dir(root)
        .args([
            "--filter",
            "@tanren/web",
            "exec",
            "prettier",
            "--stdin-filepath",
            virtual_path,
        ])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .context("spawn prettier for generated TypeScript formatting")?;

    {
        let Some(stdin) = child.stdin.as_mut() else {
            bail!("prettier stdin unavailable");
        };
        stdin
            .write_all(content.as_bytes())
            .context("write generated TypeScript into prettier stdin")?;
    }

    let output = child
        .wait_with_output()
        .context("wait for prettier formatting process")?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!(
            "prettier formatting failed for {virtual_path}: {}",
            stderr.trim()
        );
    }

    String::from_utf8(output.stdout).context("parse prettier stdout as UTF-8")
}
