use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::sync::atomic::{AtomicUsize, Ordering};

use axum::http::HeaderValue;
use chrono::Utc;
use reqwest::Client;
use sha2::{Digest, Sha256};
use tanren_api_app::build_app_with_store;
use tanren_app_services::Store;
use tanren_contract::{FileOwnership, InstallManifest, ManifestEntry};

static COUNTER: AtomicUsize = AtomicUsize::new(0);

struct TempRepo {
    path: PathBuf,
}

impl TempRepo {
    fn new(label: &str) -> Self {
        let id = COUNTER.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!("tanren-api-uninstall-test-{label}-{id}"));
        let _ = fs::remove_dir_all(&path);
        fs::create_dir_all(&path).expect("create temp repo");
        Self { path }
    }

    fn path(&self) -> &Path {
        &self.path
    }

    fn write_file(&self, rel: &str, content: &[u8]) {
        let full = self.path.join(rel);
        if let Some(parent) = full.parent() {
            let _ = fs::create_dir_all(parent);
        }
        fs::write(full, content).expect("write file");
    }

    fn file_exists(&self, rel: &str) -> bool {
        self.path.join(rel).exists()
    }

    fn read_file(&self, rel: &str) -> String {
        fs::read_to_string(self.path.join(rel)).expect("read file")
    }

    fn write_manifest(&self, manifest: &InstallManifest) {
        let dir = self.path.join(".tanren");
        fs::create_dir_all(&dir).expect("create .tanren dir");
        let json = serde_json::to_string_pretty(manifest).expect("serialize manifest");
        fs::write(dir.join("install-manifest.json"), json).expect("write manifest");
    }
}

impl Drop for TempRepo {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.path);
    }
}

fn sha256_hex(content: &[u8]) -> String {
    let digest = Sha256::digest(content);
    let mut hex = String::with_capacity(digest.len() * 2);
    for byte in digest.as_slice() {
        use std::fmt::Write;
        let _ = write!(hex, "{byte:02x}");
    }
    hex
}

struct ApiTestServer {
    base_url: String,
    client: Client,
    server: Option<tokio::task::JoinHandle<()>>,
    db_path: PathBuf,
}

impl ApiTestServer {
    async fn spawn() -> Self {
        let id = COUNTER.fetch_add(1, Ordering::Relaxed);
        let db_path = std::env::temp_dir().join(format!("tanren-api-uninstall-test-db-{id}"));
        let database_url = format!("sqlite://{}?mode=rwc", db_path.display());

        let store = Store::connect(&database_url).await.expect("connect store");
        store.migrate().await.expect("migrate store");
        let store = Arc::new(store);

        let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
            .await
            .expect("bind listener");
        let local_addr = listener.local_addr().expect("local addr");
        let base_url = format!("http://{local_addr}");

        let cors_origin = HeaderValue::from_str(&base_url).expect("cors header value");
        let app = build_app_with_store(store, &database_url, vec![cors_origin], false)
            .await
            .expect("build api app");

        let server = tokio::spawn(async move {
            let _ = axum::serve(listener, app).await;
        });

        let client = Client::builder()
            .cookie_store(true)
            .timeout(std::time::Duration::from_secs(15))
            .build()
            .expect("build reqwest client");

        Self {
            base_url,
            client,
            server: Some(server),
            db_path,
        }
    }
}

impl Drop for ApiTestServer {
    fn drop(&mut self) {
        if let Some(handle) = self.server.take() {
            handle.abort();
        }
        let _ = fs::remove_file(&self.db_path);
    }
}

#[tokio::test]
async fn api_uninstall_preview_returns_data_without_deleting_files() {
    let api = ApiTestServer::spawn().await;
    let repo = TempRepo::new("api-preview");

    let generated_content = b"generated by tanren\n";
    let generated_hash = sha256_hex(generated_content);
    repo.write_file("generated.txt", generated_content);
    repo.write_file("user-spec.md", b"my spec content\n");

    repo.write_manifest(&InstallManifest {
        version: 1,
        entries: vec![
            ManifestEntry {
                path: "generated.txt".into(),
                ownership: FileOwnership::TanrenGenerated,
                content_hash: generated_hash,
                generated_at: Utc::now(),
            },
            ManifestEntry {
                path: "user-spec.md".into(),
                ownership: FileOwnership::UserOwned,
                content_hash: sha256_hex(b"my spec content\n"),
                generated_at: Utc::now(),
            },
        ],
        created_at: Utc::now(),
    });

    let response = api
        .client
        .post(format!("{}/projects/uninstall/preview", api.base_url))
        .json(&serde_json::json!({
            "repo_path": repo.path().display().to_string()
        }))
        .send()
        .await
        .expect("POST preview");

    assert!(
        response.status().is_success(),
        "expected 2xx, got {}",
        response.status()
    );

    let body: serde_json::Value = response.json().await.expect("decode preview body");

    let to_remove = body["preview"]["to_remove"]
        .as_array()
        .expect("to_remove array");
    assert!(!to_remove.is_empty(), "preview should list files to remove");

    let preserved = body["preview"]["preserved"]
        .as_array()
        .expect("preserved array");
    assert!(
        !preserved.is_empty(),
        "preview should list files to preserve"
    );

    assert_eq!(
        body["hosted_data_unchanged"], true,
        "hosted_data_unchanged must be true"
    );

    assert!(
        repo.file_exists("generated.txt"),
        "generated.txt must still exist after preview"
    );
    assert!(
        repo.file_exists("user-spec.md"),
        "user-spec.md must still exist after preview"
    );
    assert!(
        repo.file_exists(".tanren/install-manifest.json"),
        "manifest must still exist after preview"
    );
}

#[tokio::test]
async fn api_uninstall_apply_without_confirmation_fails_and_leaves_files() {
    let api = ApiTestServer::spawn().await;
    let repo = TempRepo::new("api-no-confirm");

    let generated_content = b"generated by tanren\n";
    let generated_hash = sha256_hex(generated_content);
    repo.write_file("generated.txt", generated_content);

    repo.write_manifest(&InstallManifest {
        version: 1,
        entries: vec![ManifestEntry {
            path: "generated.txt".into(),
            ownership: FileOwnership::TanrenGenerated,
            content_hash: generated_hash,
            generated_at: Utc::now(),
        }],
        created_at: Utc::now(),
    });

    let response = api
        .client
        .post(format!("{}/projects/uninstall/apply", api.base_url))
        .json(&serde_json::json!({
            "repo_path": repo.path().display().to_string(),
            "confirm": false
        }))
        .send()
        .await
        .expect("POST apply without confirm");

    assert_eq!(
        response.status(),
        reqwest::StatusCode::BAD_REQUEST,
        "expected 400 without confirm, got {}",
        response.status()
    );

    let body: serde_json::Value = response.json().await.expect("decode error body");
    assert_eq!(
        body["code"], "confirmation_required",
        "expected confirmation_required, got {}",
        body["code"]
    );

    assert!(
        repo.file_exists("generated.txt"),
        "generated.txt must still exist after rejected apply"
    );
    assert!(
        repo.file_exists(".tanren/install-manifest.json"),
        "manifest must still exist after rejected apply"
    );
}

#[tokio::test]
async fn api_uninstall_confirmed_apply_removes_generated_preserves_user_files() {
    let api = ApiTestServer::spawn().await;
    let repo = TempRepo::new("api-confirmed-apply");

    let unchanged_content = b"generated by tanren\n";
    let unchanged_hash = sha256_hex(unchanged_content);
    repo.write_file("generated.txt", unchanged_content);

    let original_standard = b"original standard\n";
    let original_hash = sha256_hex(original_standard);
    repo.write_file("standard.md", b"edited standard content\n");

    let user_content = b"my important spec\n";
    let user_hash = sha256_hex(user_content);
    repo.write_file("user-spec.md", user_content);

    repo.write_manifest(&InstallManifest {
        version: 1,
        entries: vec![
            ManifestEntry {
                path: "generated.txt".into(),
                ownership: FileOwnership::TanrenGenerated,
                content_hash: unchanged_hash,
                generated_at: Utc::now(),
            },
            ManifestEntry {
                path: "standard.md".into(),
                ownership: FileOwnership::TanrenGenerated,
                content_hash: original_hash,
                generated_at: Utc::now(),
            },
            ManifestEntry {
                path: "user-spec.md".into(),
                ownership: FileOwnership::UserOwned,
                content_hash: user_hash,
                generated_at: Utc::now(),
            },
        ],
        created_at: Utc::now(),
    });

    let response = api
        .client
        .post(format!("{}/projects/uninstall/apply", api.base_url))
        .json(&serde_json::json!({
            "repo_path": repo.path().display().to_string(),
            "confirm": true
        }))
        .send()
        .await
        .expect("POST apply with confirm");

    assert!(
        response.status().is_success(),
        "expected 2xx, got {}",
        response.status()
    );

    let body: serde_json::Value = response.json().await.expect("decode apply body");

    assert_eq!(
        body["hosted_data_unchanged"], true,
        "hosted_data_unchanged must be true"
    );

    let removed = body["result"]["removed"].as_array().expect("removed array");
    assert!(
        !removed.is_empty(),
        "apply result should list removed files"
    );

    let preserved = body["result"]["preserved"]
        .as_array()
        .expect("preserved array");
    assert!(
        !preserved.is_empty(),
        "apply result should list preserved files"
    );

    assert!(
        !repo.file_exists("generated.txt"),
        "unchanged generated file must be removed"
    );
    assert!(
        repo.file_exists("standard.md"),
        "modified standard must be preserved"
    );
    assert_eq!(
        repo.read_file("standard.md"),
        "edited standard content\n",
        "modified standard content must be unchanged"
    );
    assert!(
        repo.file_exists("user-spec.md"),
        "user spec must be preserved"
    );
    assert_eq!(
        repo.read_file("user-spec.md"),
        "my important spec\n",
        "user spec content must be unchanged"
    );
    assert!(
        !repo.file_exists(".tanren/install-manifest.json"),
        "manifest must be removed"
    );
}
