//! TUI uninstall smoke tests — drive the `tanren-tui` binary through
//! a pseudo-terminal via `expectrl`, verifying the preview / confirm /
//! cancel flow and file-preservation guarantees.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::time::Duration;

use chrono::Utc;
use sha2::{Digest, Sha256};
use tanren_contract::{FileOwnership, InstallManifest, ManifestEntry};

static COUNTER: AtomicUsize = AtomicUsize::new(0);

struct TempRepo {
    path: PathBuf,
}

impl TempRepo {
    fn new(label: &str) -> Self {
        let id = COUNTER.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!("tanren-tui-uninstall-test-{label}-{id}"));
        let _ = fs::remove_dir_all(&path);
        fs::create_dir_all(&path).expect("create temp repo");
        Self { path }
    }

    fn path(&self) -> &Path {
        &self.path
    }

    fn write_file(&self, rel: &str, content: &[u8]) {
        let full = self.path.join(rel);
        if let Some(parent) = full.parent() {
            let _ = fs::create_dir_all(parent);
        }
        fs::write(full, content).expect("write file");
    }

    fn file_exists(&self, rel: &str) -> bool {
        self.path.join(rel).exists()
    }

    fn read_file(&self, rel: &str) -> String {
        fs::read_to_string(self.path.join(rel)).expect("read file")
    }

    fn write_manifest(&self, manifest: &InstallManifest) {
        let dir = self.path.join(".tanren");
        fs::create_dir_all(&dir).expect("create .tanren dir");
        let json = serde_json::to_string_pretty(manifest).expect("serialize manifest");
        fs::write(dir.join("install-manifest.json"), json).expect("write manifest");
    }
}

impl Drop for TempRepo {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.path);
    }
}

fn sha256_hex(content: &[u8]) -> String {
    let digest = Sha256::digest(content);
    let mut hex = String::with_capacity(digest.len() * 2);
    for byte in digest.as_slice() {
        use std::fmt::Write;
        let _ = write!(hex, "{byte:02x}");
    }
    hex
}

fn locate_tui_binary() -> PathBuf {
    if let Ok(explicit) = std::env::var("TANREN_BIN_TANREN_TUI") {
        let p = PathBuf::from(explicit);
        if p.exists() {
            return p;
        }
    }
    let exe = std::env::current_exe().expect("current exe");
    let dir = exe.parent().expect("exe parent");
    let candidate = dir.join("tanren-tui");
    if candidate.exists() {
        return candidate;
    }
    if let Some(parent) = dir.parent() {
        let parent_candidate = parent.join("tanren-tui");
        if parent_candidate.exists() {
            return parent_candidate;
        }
    }
    let fallback = dir.join("tanren-tui");
    let msg = format!(
        "tanren-tui binary not found near {} — run `cargo build -p tanren-tui`",
        exe.display(),
    );
    assert!(fallback.exists(), "{msg}");
    fallback
}

fn spawn_tui() -> expectrl::Session {
    let binary = locate_tui_binary();
    let mut cmd = Command::new(&binary);
    cmd.env("DATABASE_URL", "sqlite::memory:");
    let mut session = expectrl::Session::spawn(cmd).expect("spawn tanren-tui in pty");
    session.set_expect_timeout(Some(Duration::from_secs(10)));
    session
}

const DOWN: &[u8] = b"\x1b[B";
const ENTER: &[u8] = b"\r";

fn navigate_to_uninstall(pty: &mut expectrl::Session) {
    pty.expect("Tanren TUI").expect("wait for menu");
    pty.send(DOWN).expect("down to Sign in");
    pty.send(DOWN).expect("down to Accept invitation");
    pty.send(DOWN).expect("down to Uninstall");
    pty.send(ENTER).expect("select Uninstall");
    pty.expect("Repo path").expect("wait for uninstall form");
}

fn submit_repo_path(pty: &mut expectrl::Session, repo: &TempRepo) {
    let repo_path = repo.path().display().to_string();
    pty.send(repo_path.as_bytes()).expect("type repo path");
    pty.send(ENTER).expect("submit repo path");
    pty.expect("Files to remove").expect("wait for preview");
}

fn quit_tui(pty: &mut expectrl::Session) {
    pty.send(b"q").expect("quit from menu");
}

fn setup_mixed_repo(label: &str) -> TempRepo {
    let repo = TempRepo::new(label);

    let unchanged_content = b"generated by tanren\n";
    let unchanged_hash = sha256_hex(unchanged_content);
    repo.write_file("generated.txt", unchanged_content);

    let original_standard = b"original standard\n";
    let original_hash = sha256_hex(original_standard);
    repo.write_file("standard.md", b"edited standard content\n");

    let user_content = b"my important spec\n";
    let user_hash = sha256_hex(user_content);
    repo.write_file("user-spec.md", user_content);

    repo.write_manifest(&InstallManifest {
        version: 1,
        entries: vec![
            ManifestEntry {
                path: "generated.txt".into(),
                ownership: FileOwnership::TanrenGenerated,
                content_hash: unchanged_hash,
                generated_at: Utc::now(),
            },
            ManifestEntry {
                path: "standard.md".into(),
                ownership: FileOwnership::TanrenGenerated,
                content_hash: original_hash,
                generated_at: Utc::now(),
            },
            ManifestEntry {
                path: "user-spec.md".into(),
                ownership: FileOwnership::UserOwned,
                content_hash: user_hash,
                generated_at: Utc::now(),
            },
        ],
        created_at: Utc::now(),
    });

    repo
}

#[test]
fn tui_uninstall_preview_shows_files_and_cancel_preserves_all() {
    let repo = setup_mixed_repo("tui-preview");

    let mut pty = spawn_tui();
    navigate_to_uninstall(&mut pty);
    submit_repo_path(&mut pty, &repo);

    pty.send(b"q").expect("cancel preview");
    pty.expect("Tanren TUI").expect("returned to menu");
    quit_tui(&mut pty);

    assert!(
        repo.file_exists("generated.txt"),
        "generated.txt should still exist after cancel",
    );
    assert!(
        repo.file_exists("standard.md"),
        "standard.md should still exist after cancel",
    );
    assert!(
        repo.file_exists("user-spec.md"),
        "user-spec.md should still exist after cancel",
    );
    assert!(
        repo.file_exists(".tanren/install-manifest.json"),
        "manifest should still exist after cancel",
    );
}

#[test]
fn tui_uninstall_confirmed_apply_removes_generated_preserves_user_files() {
    let repo = setup_mixed_repo("tui-confirmed");

    let mut pty = spawn_tui();
    navigate_to_uninstall(&mut pty);
    submit_repo_path(&mut pty, &repo);

    pty.send(ENTER).expect("confirm uninstall");
    pty.expect("Uninstall applied").expect("wait for outcome");

    pty.send(b"q").expect("dismiss outcome to menu");
    pty.expect("Tanren TUI").expect("back at menu");
    quit_tui(&mut pty);

    assert!(
        !repo.file_exists("generated.txt"),
        "unchanged generated file should be removed",
    );
    assert!(
        repo.file_exists("standard.md"),
        "modified standard should be preserved",
    );
    assert_eq!(
        repo.read_file("standard.md"),
        "edited standard content\n",
        "modified standard content should be unchanged",
    );
    assert!(
        repo.file_exists("user-spec.md"),
        "user spec should be preserved",
    );
    assert_eq!(
        repo.read_file("user-spec.md"),
        "my important spec\n",
        "user spec content should be unchanged",
    );
    assert!(
        !repo.file_exists(".tanren/install-manifest.json"),
        "manifest should be removed",
    );
}
