"""initial schema

Revision ID: 3c64b1f6c2ae
Revises:
Create Date: 2026-03-30 14:27:24.322681

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c64b1f6c2ae"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dispatch_projection",
        sa.Column("dispatch_id", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("lane", sa.String(), nullable=False),
        sa.Column("preserve_on_failure", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("dispatch_json", sa.JSON(), nullable=False),
        sa.Column("user_id", sa.String(), server_default="", nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("dispatch_id"),
    )
    op.create_index("idx_dispatch_created", "dispatch_projection", ["created_at"], unique=False)
    op.create_index("idx_dispatch_lane", "dispatch_projection", ["lane"], unique=False)
    op.create_index("idx_dispatch_status", "dispatch_projection", ["status"], unique=False)
    op.create_index("idx_dispatch_user", "dispatch_projection", ["user_id"], unique=False)
    op.create_table(
        "events",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), server_default="dispatch", nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index("idx_events_entity", "events", ["entity_id"], unique=False)
    op.create_index("idx_events_entity_type", "events", ["entity_type"], unique=False)
    op.create_index("idx_events_timestamp", "events", ["timestamp"], unique=False)
    op.create_index("idx_events_type", "events", ["event_type"], unique=False)
    op.create_table(
        "user_projection",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("role", sa.String(), server_default="member", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "vm_assignments",
        sa.Column("vm_id", sa.String(), nullable=False),
        sa.Column("workflow_id", sa.String(), nullable=False),
        sa.Column("project", sa.String(), nullable=False),
        sa.Column("spec", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("assigned_at", sa.String(), nullable=False),
        sa.Column("released_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("vm_id"),
    )
    op.create_index(
        "idx_vm_active",
        "vm_assignments",
        ["released_at"],
        unique=False,
        sqlite_where=sa.text("released_at IS NULL"),
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.create_table(
        "api_key_projection",
        sa.Column("key_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("key_prefix", sa.String(), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("resource_limits", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("expires_at", sa.String(), nullable=True),
        sa.Column("revoked_at", sa.String(), nullable=True),
        sa.Column("grace_replaced_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_projection.user_id"],
        ),
        sa.PrimaryKeyConstraint("key_id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index("idx_key_hash", "api_key_projection", ["key_hash"], unique=True)
    op.create_index("idx_key_prefix", "api_key_projection", ["key_prefix"], unique=False)
    op.create_index("idx_key_user", "api_key_projection", ["user_id"], unique=False)
    op.create_table(
        "step_projection",
        sa.Column("step_id", sa.String(), nullable=False),
        sa.Column("dispatch_id", sa.String(), nullable=False),
        sa.Column("step_type", sa.String(), nullable=False),
        sa.Column("step_sequence", sa.Integer(), nullable=False),
        sa.Column("lane", sa.String(), nullable=True),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("worker_id", sa.String(), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dispatch_id"],
            ["dispatch_projection.dispatch_id"],
        ),
        sa.PrimaryKeyConstraint("step_id"),
    )
    op.create_index("idx_step_dispatch", "step_projection", ["dispatch_id"], unique=False)
    op.create_index("idx_step_lane_status", "step_projection", ["lane", "status"], unique=False)
    op.create_index("idx_step_status", "step_projection", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_step_status", table_name="step_projection")
    op.drop_index("idx_step_lane_status", table_name="step_projection")
    op.drop_index("idx_step_dispatch", table_name="step_projection")
    op.drop_table("step_projection")
    op.drop_index("idx_key_user", table_name="api_key_projection")
    op.drop_index("idx_key_prefix", table_name="api_key_projection")
    op.drop_index("idx_key_hash", table_name="api_key_projection")
    op.drop_table("api_key_projection")
    op.drop_index(
        "idx_vm_active",
        table_name="vm_assignments",
        sqlite_where=sa.text("released_at IS NULL"),
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.drop_table("vm_assignments")
    op.drop_table("user_projection")
    op.drop_index("idx_events_type", table_name="events")
    op.drop_index("idx_events_timestamp", table_name="events")
    op.drop_index("idx_events_entity_type", table_name="events")
    op.drop_index("idx_events_entity", table_name="events")
    op.drop_table("events")
    op.drop_index("idx_dispatch_user", table_name="dispatch_projection")
    op.drop_index("idx_dispatch_status", table_name="dispatch_projection")
    op.drop_index("idx_dispatch_lane", table_name="dispatch_projection")
    op.drop_index("idx_dispatch_created", table_name="dispatch_projection")
    op.drop_table("dispatch_projection")
    # ### end Alembic commands ###
