/* eslint-disable */
// This file is auto-generated by apps/web/scripts/generate-api-contract.mjs.
// Do not make direct changes to this file.

import * as v from "valibot";

const signUpRequestComponentSchema = v.lazy(() =>
  v.object({
    display_name: v.string(),
    email: emailComponentSchema,
    password: v.string(),
  }),
);
const signUpResponseCookieComponentSchema = v.lazy(() =>
  v.object({
    account: accountViewComponentSchema,
    session: cookieSessionEnvelopeComponentSchema,
  }),
);
const healthResponseComponentSchema = v.lazy(() =>
  v.object({
    contract_version: v.pipe(v.number(), v.integer(), v.minValue(0)),
    status: v.string(),
    version: v.string(),
  }),
);
const acceptInvitationBodyComponentSchema = v.lazy(() =>
  v.object({
    display_name: v.string(),
    email: emailComponentSchema,
    password: v.string(),
  }),
);
const acceptInvitationResponseCookieComponentSchema = v.lazy(() =>
  v.object({
    account: accountViewComponentSchema,
    joined_org: orgIdComponentSchema,
    session: cookieSessionEnvelopeComponentSchema,
  }),
);
const activeProjectCookieRequestComponentSchema = v.lazy(() =>
  v.strictObject({}),
);
const activeProjectViewComponentSchema = v.lazy(() =>
  v.object({
    active_project: v.exactOptional(
      v.union([v.null(), projectViewComponentSchema]),
    ),
    owning_account_id: accountIdComponentSchema,
  }),
);
const connectProjectRepositoryCookieRequestComponentSchema = v.lazy(() =>
  v.strictObject({
    repository: repositoryRefComponentSchema,
    select_as_active: v.boolean(),
  }),
);
const connectProjectRepositoryResponseComponentSchema = v.lazy(() =>
  v.object({
    project: projectViewComponentSchema,
  }),
);
const createProjectCookieRequestComponentSchema = v.lazy(() =>
  v.strictObject({
    designated_host: designatedHostComponentSchema,
    repository: repositoryRefComponentSchema,
    select_as_active: v.boolean(),
  }),
);
const createProjectResponseComponentSchema = v.lazy(() =>
  v.object({
    project: projectViewComponentSchema,
  }),
);
const listVisibleProjectsCookieRequestComponentSchema = v.lazy(() =>
  v.strictObject({
    page: v.exactOptional(projectPageRequestComponentSchema),
  }),
);
const projectCollectionViewComponentSchema = v.lazy(() =>
  v.object({
    freshness: projectCollectionFreshnessViewComponentSchema,
    owning_account_id: accountIdComponentSchema,
    pagination: projectPaginationViewComponentSchema,
    projects: v.array(projectViewComponentSchema),
  }),
);
const signInRequestComponentSchema = v.lazy(() =>
  v.object({
    email: emailComponentSchema,
    password: v.string(),
  }),
);
const signInResponseCookieComponentSchema = v.lazy(() =>
  v.object({
    account: accountViewComponentSchema,
    session: cookieSessionEnvelopeComponentSchema,
  }),
);
const emailComponentSchema = v.lazy(() => v.pipe(v.string(), v.email()));
const accountViewComponentSchema = v.lazy(() =>
  v.object({
    display_name: v.string(),
    id: accountIdComponentSchema,
    identifier: identifierComponentSchema,
    org: v.exactOptional(v.union([v.null(), orgIdComponentSchema])),
  }),
);
const cookieSessionEnvelopeComponentSchema = v.lazy(() =>
  v.union([
    v.object({
      account_id: accountIdComponentSchema,
      expires_at: v.string(),
      transport: v.picklist(["cookie"]),
    }),
  ]),
);
const orgIdComponentSchema = v.lazy(() => v.string());
const projectViewComponentSchema = v.lazy(() =>
  v.object({
    counts: projectCountsViewComponentSchema,
    created_at: v.string(),
    id: projectIdComponentSchema,
    owning_account_id: accountIdComponentSchema,
    repository: projectRepositoryViewComponentSchema,
    selection: projectSelectionViewComponentSchema,
  }),
);
const accountIdComponentSchema = v.lazy(() => v.string());
const repositoryRefComponentSchema = v.lazy(() =>
  v.pipe(
    v.string(),
    v.regex(
      new RegExp(
        "^[a-z0-9](?:[a-z0-9-]{0,37}[a-z0-9])?/[a-z0-9](?:[a-z0-9._-]{0,98}[a-z0-9])?$",
      ),
    ),
  ),
);
const designatedHostComponentSchema = v.lazy(() =>
  v.pipe(
    v.string(),
    v.regex(
      new RegExp(
        "^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)(?:\\.(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?))*$",
      ),
    ),
  ),
);
const projectPageRequestComponentSchema = v.lazy(() =>
  v.strictObject({
    cursor: v.exactOptional(
      v.union([v.null(), projectListCursorComponentSchema]),
    ),
    filter: v.exactOptional(projectListFilterRequestComponentSchema),
    page_size: v.exactOptional(
      v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(100)),
    ),
    sort: v.exactOptional(projectListSortRequestComponentSchema),
  }),
);
const projectCollectionFreshnessViewComponentSchema = v.lazy(() =>
  v.object({
    as_of: v.exactOptional(v.nullable(v.string())),
  }),
);
const projectPaginationViewComponentSchema = v.lazy(() =>
  v.object({
    default_page_size: v.pipe(v.number(), v.integer(), v.minValue(0)),
    has_more: v.boolean(),
    max_page_size: v.pipe(v.number(), v.integer(), v.minValue(0)),
    next_cursor: v.exactOptional(
      v.union([v.null(), projectListCursorComponentSchema]),
    ),
    page_size: v.pipe(v.number(), v.integer(), v.minValue(0)),
  }),
);
const identifierComponentSchema = v.lazy(() => v.string());
const projectCountsViewComponentSchema = v.lazy(() =>
  v.object({
    initiatives: v.pipe(v.number(), v.integer(), v.minValue(0)),
    milestones: v.pipe(v.number(), v.integer(), v.minValue(0)),
    specs: v.pipe(v.number(), v.integer(), v.minValue(0)),
  }),
);
const projectIdComponentSchema = v.lazy(() => v.string());
const projectRepositoryViewComponentSchema = v.lazy(() =>
  v.object({
    repository: repositoryRefComponentSchema,
    source_control_host: designatedHostComponentSchema,
  }),
);
const projectSelectionViewComponentSchema = v.lazy(() =>
  v.object({
    is_active: v.boolean(),
    selected_at: v.exactOptional(v.nullable(v.string())),
  }),
);
const projectListCursorComponentSchema = v.lazy(() =>
  v.strictObject({
    active_selected_at: v.exactOptional(v.nullable(v.string())),
    created_at: v.string(),
    project_id: projectIdComponentSchema,
  }),
);
const projectListFilterRequestComponentSchema = v.lazy(() =>
  v.strictObject({
    selection: v.exactOptional(projectListSelectionFilterComponentSchema),
  }),
);
const projectListSortRequestComponentSchema = v.lazy(() =>
  v.strictObject({
    order: v.exactOptional(projectListSortOrderComponentSchema),
  }),
);
const projectListSelectionFilterComponentSchema = v.lazy(() =>
  v.picklist(["all"]),
);
const projectListSortOrderComponentSchema = v.lazy(() =>
  v.picklist(["active_selected_then_created_desc"]),
);

export const signUpRequestSchema = signUpRequestComponentSchema;
export const signUpResponseSchema = signUpResponseCookieComponentSchema;
export const healthResponseSchema = healthResponseComponentSchema;
export const acceptInvitationRequestSchema =
  acceptInvitationBodyComponentSchema;
export const acceptInvitationResponseSchema =
  acceptInvitationResponseCookieComponentSchema;
export const activeProjectRequestSchema =
  activeProjectCookieRequestComponentSchema;
export const activeProjectResponseSchema = activeProjectViewComponentSchema;
export const connectProjectRepositoryRequestSchema =
  connectProjectRepositoryCookieRequestComponentSchema;
export const connectProjectRepositoryResponseSchema =
  connectProjectRepositoryResponseComponentSchema;
export const createProjectRequestSchema =
  createProjectCookieRequestComponentSchema;
export const createProjectResponseSchema = createProjectResponseComponentSchema;
export const listVisibleProjectsRequestSchema =
  listVisibleProjectsCookieRequestComponentSchema;
export const listVisibleProjectsResponseSchema =
  projectCollectionViewComponentSchema;
export const signInRequestSchema = signInRequestComponentSchema;
export const signInResponseSchema = signInResponseCookieComponentSchema;
