/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/accounts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sign_up_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/invitations/{token}/accept": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["accept_invitation_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/active": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["active_project_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/connect-repository": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["connect_project_repository_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_project_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["list_visible_projects_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sign_in_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/revoke": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["revoke_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AcceptInvitationBody: {
      display_name: string;
      email: components["schemas"]["Email"];
      /** Format: password */
      password: string;
    };
    AcceptInvitationResponseCookie: {
      account: components["schemas"]["AccountView"];
      joined_org: components["schemas"]["OrgId"];
      session: components["schemas"]["CookieSessionEnvelope"];
    };
    /** @description Shared `{code, summary}` failure body. */
    AccountFailureBody: {
      /** @description Stable error code from the closed taxonomy. */
      code: components["schemas"]["AccountFailureCode"];
      /** @description Human-readable summary. */
      summary: string;
    };
    /** @description Wire-visible account failure codes for `{code, summary}` error bodies. */
    AccountFailureCode:
      | "duplicate_identifier"
      | "invalid_credential"
      | "validation_failed"
      | "invitation_not_found"
      | "invitation_expired"
      | "invitation_already_consumed"
      | "auth_required"
      | "internal_error";
    /**
     * Format: uuid
     * @description Stable identifier for a Tanren account. `UUIDv7` — sortable + unique.
     */
    AccountId: string;
    /** @description External-facing view of a Tanren account. */
    AccountView: {
      /** @description Display name. */
      display_name: string;
      /** @description Stable account id. */
      id: components["schemas"]["AccountId"];
      /** @description User-facing identifier (email). */
      identifier: components["schemas"]["Identifier"];
      org?: null | components["schemas"]["OrgId"];
    };
    /** @description Cookie-scoped API/web request for active-project metadata. */
    ActiveProjectCookieRequest: Record<string, never>;
    /** @description Active-project projection for an account. */
    ActiveProjectView: {
      active_project?: null | components["schemas"]["ProjectView"];
      /** @description Account that owns this active-project view. */
      owning_account_id: components["schemas"]["AccountId"];
    };
    /** @description Cookie-scoped API/web request for connecting an existing repository. */
    ConnectProjectRepositoryCookieRequest: {
      /** @description Canonical repository identity (`owner/name`). */
      repository: components["schemas"]["RepositoryRef"];
      /** @description Whether the newly connected project should be active immediately. */
      select_as_active: boolean;
    };
    /** @description Successful repository-connection response. */
    ConnectProjectRepositoryResponse: {
      /** @description Newly connected project. */
      project: components["schemas"]["ProjectView"];
    };
    /** @description Cookie-scoped API/web request for creating a project. */
    CreateProjectCookieRequest: {
      /** @description Designated host where the repository should be created. */
      designated_host: string;
      /** @description Canonical repository identity (`owner/name`) to create. */
      repository: components["schemas"]["RepositoryRef"];
      /** @description Whether the newly created project should be active immediately. */
      select_as_active: boolean;
    };
    /** @description Successful project-creation response. */
    CreateProjectResponse: {
      /** @description Newly created project. */
      project: components["schemas"]["ProjectView"];
    };
    /**
     * Format: email
     * @description Validated email address. Constructed via [`Email::parse`] which:
     *     trims surrounding whitespace, validates against RFC 5322 syntax via
     *     the [`email_validator_rfc5322`] crate (RFC 5321 length limits +
     *     quoted local parts), additionally requires a TLD-style domain (no
     *     dotless or IP-literal domains), and canonicalises to lower-case so
     *     case variants of the same address compare equal.
     *
     *     # Wire-input contract
     *
     *     `Email` does NOT derive `Deserialize` — the custom impl below routes
     *     every wire input through [`parse`](Self::parse). Without this,
     *     `#[serde(transparent)]` would let HTTP/MCP/CLI requests carry
     *     untrimmed/un-lowercased/RFC-invalid addresses, which would persist
     *     verbatim via `Identifier::from_email` and let two case variants of
     *     the same logical email register as separate accounts. Codex P1
     *     review on PR #133.
     *
     *     Validation invariants are exercised end-to-end by the @api / @web
     *     scenarios in `tests/bdd/features/B-0043-create-account.feature` —
     *     case-variant rejection and malformed-email rejection both run
     *     through the live wire surface, not through Rust unit tests.
     */
    Email: string;
    HealthResponse: {
      /** Format: int32 */
      contract_version: number;
      status: string;
      version: string;
    };
    /**
     * @description User-facing identifier for an account. R-0001's chosen mechanism is
     *     identifier+password where the identifier is the canonical email; the
     *     type wraps the raw string so future mechanisms can lift constraints
     *     in one place.
     *
     *     `Identifier` does NOT derive `Deserialize` — the custom impl below
     *     routes every wire input through [`parse`](Self::parse) so untrimmed
     *     or differently-cased identifiers cannot bypass canonicalisation.
     *     Validation invariants are exercised end-to-end by the @api / @web
     *     scenarios in `tests/bdd/features/B-0043-create-account.feature`
     *     (case-variant rejection, malformed-input rejection); per the
     *     BDD-only test surface policy there are no Rust unit or doc-tests
     *     for these rules.
     */
    Identifier: string;
    /**
     * @description Cookie-scoped API/web request for listing projects visible to the
     *     authenticated session account.
     */
    ListVisibleProjectsCookieRequest: {
      /** @description Pagination controls for this list request. */
      page?: components["schemas"]["ProjectPageRequest"];
    };
    /**
     * Format: uuid
     * @description Stable identifier for a Tanren organization.
     */
    OrgId: string;
    /** @description Wire projection for a project list/read response. */
    ProjectCollectionView: {
      /** @description Projection freshness metadata for this page. */
      freshness: components["schemas"]["ProjectCollectionFreshnessView"];
      /** @description Account that owns this collection. */
      owning_account_id: components["schemas"]["AccountId"];
      /** @description Bounded pagination metadata for this page. */
      pagination: components["schemas"]["ProjectPaginationView"];
      /** @description Projects currently visible under the account. */
      projects: components["schemas"]["ProjectView"][];
    };
    /** @description Projection freshness metadata for project lists. */
    ProjectCollectionFreshnessView: {
      /**
       * Format: date-time
       * @description The newest row timestamp visible in this page (if any rows exist).
       */
      as_of?: string | null;
    };
    /** @description Aggregated counts surfaced alongside project records. */
    ProjectCountsView: {
      /**
       * Format: int64
       * @description Number of initiatives in this project.
       */
      initiatives: number;
      /**
       * Format: int64
       * @description Number of milestones in this project.
       */
      milestones: number;
      /**
       * Format: int64
       * @description Number of specs in this project.
       */
      specs: number;
    };
    /** @description Shared `{code, summary}` project-failure body. */
    ProjectFailureBody: {
      /** @description Stable error code from the closed taxonomy. */
      code: components["schemas"]["ProjectFailureCode"];
      /** @description Human-readable summary. */
      summary: string;
    };
    /** @description Wire-visible project failure codes for `{code, summary}` error bodies. */
    ProjectFailureCode:
      | "auth_required"
      | "duplicate_repository"
      | "in_flight"
      | "rate_limited"
      | "no_access"
      | "validation_failed"
      | "provider_unavailable"
      | "provider_failure"
      | "internal_error";
    /**
     * Format: uuid
     * @description Stable identifier for a Tanren project. `UUIDv7` — sortable + unique.
     */
    ProjectId: string;
    /** @description Stable cursor over the deterministic project-list ordering. */
    ProjectListCursor: {
      /**
       * Format: date-time
       * @description Active-selection timestamp used as the primary sort key.
       */
      active_selected_at?: string | null;
      /**
       * Format: date-time
       * @description Project creation timestamp used as a secondary sort key.
       */
      created_at: string;
      /** @description Project id used as a final deterministic tie-breaker. */
      project_id: components["schemas"]["ProjectId"];
    };
    /** @description Explicit filter fields supported by the project-list contract. */
    ProjectListFilterRequest: {
      /** @description Selection-state filter for visible projects. */
      selection?: components["schemas"]["ProjectListSelectionFilter"];
    };
    /**
     * @description Supported project-list selection filters.
     * @enum {string}
     */
    ProjectListSelectionFilter: "all";
    /** @description Explicit sort fields supported by the project-list contract. */
    ProjectListSortRequest: {
      /** @description Deterministic ordering for visible projects. */
      order?: components["schemas"]["ProjectListSortOrder"];
    };
    /**
     * @description Supported deterministic orderings for project-list pagination.
     * @enum {string}
     */
    ProjectListSortOrder: "active_selected_then_created_desc";
    /** @description Pagination controls for project-list queries. */
    ProjectPageRequest: {
      /** @description Cursor pointing to the last project from the previous page. */
      cursor?: null | components["schemas"]["ProjectListCursor"];
      /** @description Filter controls for this list request. */
      filter?: components["schemas"]["ProjectListFilterRequest"];
      /**
       * @description Requested page size, bounded server-side to `[1, max_page_size]`.
       * @minimum 1
       * @maximum 100
       * @default 25
       */
      page_size?: number;
      /** @description Sort controls for this list request. */
      sort?: components["schemas"]["ProjectListSortRequest"];
    };
    /** @description Pagination metadata for a project-list response page. */
    ProjectPaginationView: {
      /** @description Default server page size when callers omit one. */
      default_page_size: number;
      /** @description Whether another page exists after this one. */
      has_more: boolean;
      /** @description Maximum server page size. */
      max_page_size: number;
      /** @description Cursor callers should send to request the next page. */
      next_cursor?: null | components["schemas"]["ProjectListCursor"];
      /** @description The page size that was actually applied after bounding. */
      page_size: number;
    };
    /** @description Repository metadata bound to a project. */
    ProjectRepositoryView: {
      /** @description Source-control host where this repository is bound. */
      source_control_host: string;
      /** @description Canonical `owner/name` repository identity. */
      repository: components["schemas"]["RepositoryRef"];
    };
    /** @description Metadata about active-project selection state. */
    ProjectSelectionView: {
      /** @description Whether this project is currently active for the owning account. */
      is_active: boolean;
      /**
       * Format: date-time
       * @description Wall-clock time this project became active, if active.
       */
      selected_at?: string | null;
    };
    /** @description External-facing project projection. */
    ProjectView: {
      /** @description Current aggregate counts for neighboring planning subsystems. */
      counts: components["schemas"]["ProjectCountsView"];
      /**
       * Format: date-time
       * @description Wall-clock time the project was created.
       */
      created_at: string;
      /** @description Stable project id. */
      id: components["schemas"]["ProjectId"];
      /** @description Account that owns the project. */
      owning_account_id: components["schemas"]["AccountId"];
      /** @description Repository connected to the project. */
      repository: components["schemas"]["ProjectRepositoryView"];
      /** @description Active-project selection metadata. */
      selection: components["schemas"]["ProjectSelectionView"];
    };
    /**
     * @description Canonical repository identity (`owner/name`) used for project setup.
     *
     *     The value is lower-cased + trimmed during parse so different case
     *     spellings of the same repository map to one canonical key.
     */
    RepositoryRef: string;
    /**
     * @description Cookie-transport session envelope for API/web account responses.
     *
     *     Session tokens are written to an `HttpOnly` cookie and are never
     *     returned in these response bodies.
     */
    CookieSessionEnvelope: {
      /** @description Account this session is bound to. */
      account_id: components["schemas"]["AccountId"];
      /**
       * Format: date-time
       * @description Wall-clock time at which the session expires.
       */
      expires_at: string;
      /** @enum {string} */
      transport: "cookie";
    };
    /** @description Sign-in request. */
    SignInRequest: {
      /** @description Email of the account being signed in to. */
      email: components["schemas"]["Email"];
      /**
       * Format: password
       * @description Plaintext password — verified against the stored hash.
       */
      password: string;
    };
    SignInResponseCookie: {
      account: components["schemas"]["AccountView"];
      session: components["schemas"]["CookieSessionEnvelope"];
    };
    /** @description Self-signup request. */
    SignUpRequest: {
      /** @description Human-readable display name for the new account. */
      display_name: string;
      /**
       * @description Email address that will own the new account. Lower-cased + trimmed
       *     during validation.
       */
      email: components["schemas"]["Email"];
      /**
       * Format: password
       * @description Plaintext password. Hashed by the handler before persistence.
       *     Wrapped in `SecretString` so accidental `Debug` / `Serialize`
       *     calls do not leak the credential.
       */
      password: string;
    };
    SignUpResponseCookie: {
      account: components["schemas"]["AccountView"];
      session: components["schemas"]["CookieSessionEnvelope"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
  securitySchemes: {
    tanren_session: {
      /** @enum {string} */
      in: "cookie";
      name: "tanren_session";
      /** @enum {string} */
      type: "apiKey";
    };
  };
}
export type $defs = Record<string, never>;
export interface operations {
  sign_up_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignUpRequest"];
      };
    };
    responses: {
      /** @description Account created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SignUpResponseCookie"];
        };
      };
      /** @description validation_failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountFailureBody"];
        };
      };
      /** @description invalid_credential */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountFailureBody"];
        };
      };
      /** @description duplicate_identifier */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountFailureBody"];
        };
      };
    };
  };
  health_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is live */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  accept_invitation_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Opaque invitation token */
        token: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcceptInvitationBody"];
      };
    };
    responses: {
      /** @description Invitation accepted */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AcceptInvitationResponseCookie"];
        };
      };
      /** @description validation_failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountFailureBody"];
        };
      };
      /** @description invitation_not_found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountFailureBody"];
        };
      };
      /** @description invitation_expired or invitation_already_consumed */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountFailureBody"];
        };
      };
    };
  };
  active_project_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActiveProjectCookieRequest"];
      };
    };
    security: {
      tanren_session: string[];
    }[];
    responses: {
      /** @description Active-project metadata */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActiveProjectView"];
        };
      };
      /** @description validation_failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
      /** @description auth_required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
      /** @description no_access */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
    };
  };
  connect_project_repository_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConnectProjectRepositoryCookieRequest"];
      };
    };
    security: {
      tanren_session: string[];
    }[];
    responses: {
      /** @description Repository connected as project */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnectProjectRepositoryResponse"];
        };
      };
      /** @description validation_failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
      /** @description auth_required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
      /** @description no_access */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
      /** @description duplicate_repository */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
      /** @description rate_limited */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
      /** @description provider_failure */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
    };
  };
  create_project_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateProjectCookieRequest"];
      };
    };
    security: {
      tanren_session: string[];
    }[];
    responses: {
      /** @description Project and repository created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateProjectResponse"];
        };
      };
      /** @description validation_failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
      /** @description auth_required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
      /** @description no_access */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
      /** @description duplicate_repository */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
      /** @description rate_limited */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
      /** @description provider_failure */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
    };
  };
  list_visible_projects_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ListVisibleProjectsCookieRequest"];
      };
    };
    security: {
      tanren_session: string[];
    }[];
    responses: {
      /** @description Project list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectCollectionView"];
        };
      };
      /** @description validation_failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
      /** @description auth_required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
      /** @description no_access */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFailureBody"];
        };
      };
    };
  };
  sign_in_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInRequest"];
      };
    };
    responses: {
      /** @description Sign-in succeeded */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SignInResponseCookie"];
        };
      };
      /** @description validation_failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountFailureBody"];
        };
      };
      /** @description invalid_credential */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountFailureBody"];
        };
      };
    };
  };
  revoke_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
