//! `xtask check-openapi-drift` — fail when the committed `OpenAPI` artifact
//! has diverged from what the Rust code would produce.
//!
//! The canonical `OpenAPI` artifact lives at `artifacts/openapi.json` and is
//! generated by the `export-openapi` binary in `tanren-api-app`. It is
//! committed so that downstream consumers (web build, IDE intellisense)
//! work without running the Rust toolchain. This guard regenerates the
//! spec and compares it against the committed copy, failing on any
//! difference so checked-in generated files cannot silently drift from the
//! Rust source of truth.

use anyhow::{Context, Result, bail};
use std::fs;
use std::io::Write;
use std::path::Path;
use std::process::Command;

const ARTIFACT_RELATIVE: &str = "artifacts/openapi.json";

pub(crate) fn run(root: &Path) -> Result<()> {
    let artifact_path = root.join(ARTIFACT_RELATIVE);
    if !artifact_path.exists() {
        bail!(
            "check-openapi-drift: {ARTIFACT_RELATIVE} does not exist — run `just export-openapi`"
        );
    }

    let fresh_spec = export_spec(root)?;

    let committed_spec = fs::read_to_string(&artifact_path)
        .with_context(|| format!("read {}", artifact_path.display()))?;

    if committed_spec == fresh_spec {
        let stdout = std::io::stdout();
        let mut handle = stdout.lock();
        let _ = writeln!(
            handle,
            "check-openapi-drift: committed artifact matches Rust source"
        );
        return Ok(());
    }

    bail!(
        "check-openapi-drift: {ARTIFACT_RELATIVE} has diverged from the Rust-generated spec — run `just export-openapi`"
    );
}

fn export_spec(root: &Path) -> Result<String> {
    let output = Command::new("cargo")
        .args([
            "run",
            "-p",
            "tanren-api-app",
            "--bin",
            "export-openapi",
            "--locked",
            "--quiet",
        ])
        .current_dir(root)
        .output()
        .context("spawn cargo run -p tanren-api-app --bin export-openapi")?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!("export-openapi failed: {stderr}");
    }
    String::from_utf8(output.stdout).context("export-openapi output is not valid UTF-8")
}
