//! `xtask generate-web-contracts` — emit web account contract types and
//! runtime validators from Rust JSON Schema sources.

use anyhow::{Context, Result};
use schemars::schema_for;
use serde_json::{Map, Value, json};
use std::collections::{BTreeSet, HashSet};
use std::fmt::Write as _;
use std::fs;
use std::io::Write;
use std::path::Path;
use tanren_contract::{
    AccountFailureReason, AccountView, ActiveAccountView, ListActiveAccountsRequest,
    ListActiveAccountsResponse, SessionEnvelope, SignedInAccountView, SwitchActiveAccountRequest,
    SwitchActiveAccountResponse,
};
use tanren_identity_policy::{AccountId, Identifier, OrgId};

const OUTPUT_PATH: &str = "apps/web/src/app/lib/generated/account-contract.ts";

pub(crate) fn run(root: &Path) -> Result<()> {
    let output = root.join(OUTPUT_PATH);
    let parent = output
        .parent()
        .context("generated web contract path has no parent")?;
    fs::create_dir_all(parent)
        .with_context(|| format!("create generated dir {}", parent.display()))?;

    let contents = render_contract_file();
    fs::write(&output, contents).with_context(|| format!("write {}", output.display()))?;

    let stdout = std::io::stdout();
    let mut handle = stdout.lock();
    let _ = writeln!(handle, "generate-web-contracts: wrote {}", output.display());
    Ok(())
}

#[derive(Debug)]
struct SchemaTarget {
    name: &'static str,
    schema: Value,
    brand: Option<&'static str>,
}

fn render_contract_file() -> String {
    let targets = schema_targets();
    let mut rendered = String::new();
    render_header(&mut rendered);
    render_schema_exports(&mut rendered, &targets);
    render_parse_helpers(&mut rendered, &targets);
    render_failure_code_union(&mut rendered);
    rendered
}

fn schema_targets() -> Vec<SchemaTarget> {
    vec![
        SchemaTarget {
            name: "AccountId",
            schema: schema_json::<AccountId>(),
            brand: Some("AccountId"),
        },
        SchemaTarget {
            name: "OrgId",
            schema: schema_json::<OrgId>(),
            brand: Some("OrgId"),
        },
        SchemaTarget {
            name: "Identifier",
            schema: schema_json::<Identifier>(),
            brand: None,
        },
        SchemaTarget {
            name: "AccountView",
            schema: schema_json::<AccountView>(),
            brand: None,
        },
        SchemaTarget {
            name: "ActiveAccountView",
            schema: schema_json::<ActiveAccountView>(),
            brand: None,
        },
        SchemaTarget {
            name: "SignedInAccountView",
            schema: schema_json::<SignedInAccountView>(),
            brand: None,
        },
        SchemaTarget {
            name: "SessionEnvelope",
            schema: schema_json::<SessionEnvelope>(),
            brand: None,
        },
        SchemaTarget {
            name: "ListActiveAccountsRequest",
            schema: schema_json::<ListActiveAccountsRequest>(),
            brand: None,
        },
        SchemaTarget {
            name: "ListActiveAccountsResponse",
            schema: schema_json::<ListActiveAccountsResponse>(),
            brand: None,
        },
        SchemaTarget {
            name: "SwitchActiveAccountRequest",
            schema: schema_json::<SwitchActiveAccountRequest>(),
            brand: None,
        },
        SchemaTarget {
            name: "SwitchActiveAccountResponse",
            schema: schema_json::<SwitchActiveAccountResponse>(),
            brand: None,
        },
    ]
}

fn render_header(rendered: &mut String) {
    rendered
        .push_str("// Generated by `cargo run -q -p tanren-xtask -- generate-web-contracts`.\n");
    rendered.push_str(
        "// Source of truth: `tanren-contract`/`tanren-identity-policy` JsonSchema derives.\n\n",
    );
    rendered.push_str("import * as v from \"valibot\";\n\n");
    rendered.push_str("export type Brand<TValue, TBrand extends string> = TValue & {\n");
    rendered.push_str("  readonly __brand: TBrand;\n");
    rendered.push_str("};\n\n");
}

fn render_schema_exports(rendered: &mut String, targets: &[SchemaTarget]) {
    let known_top_level_names = targets
        .iter()
        .map(|target| target.name.to_owned())
        .collect::<BTreeSet<_>>();
    for target in targets {
        let defs = schema_definitions(&target.schema);
        let mut stack = Vec::new();
        let schema_expr = schema_to_valibot(
            &target.schema,
            &defs,
            &known_top_level_names,
            &mut stack,
            target.brand,
        );
        let _ = writeln!(
            rendered,
            "export const {}Schema = {};",
            target.name, schema_expr
        );
        let _ = writeln!(
            rendered,
            "export type {} = v.InferOutput<typeof {}Schema>;\n",
            target.name, target.name
        );
    }
}

fn render_parse_helpers(rendered: &mut String, targets: &[SchemaTarget]) {
    rendered.push_str("function parseWithSchema<\n");
    rendered.push_str("  TSchema extends v.BaseSchema<unknown, unknown, v.BaseIssue<unknown>>,\n");
    rendered.push_str(">(schema: TSchema, payload: unknown): v.InferOutput<TSchema> | null {\n");
    rendered.push_str("  const parsed = v.safeParse(schema, payload);\n");
    rendered.push_str("  if (!parsed.success) {\n");
    rendered.push_str("    return null;\n");
    rendered.push_str("  }\n");
    rendered.push_str("  return parsed.output;\n");
    rendered.push_str("}\n\n");

    for target in targets {
        let _ = writeln!(
            rendered,
            "export function parse{}(payload: unknown): {} | null {{",
            target.name, target.name
        );
        let _ = writeln!(
            rendered,
            "  return parseWithSchema({}Schema, payload);",
            target.name
        );
        rendered.push_str("}\n\n");
    }
}

fn render_failure_code_union(rendered: &mut String) {
    rendered.push_str("export type AccountFailureCode =\n");
    for reason in AccountFailureReason::all() {
        let _ = writeln!(rendered, "  | \"{}\"", reason.code());
    }
    rendered.push_str(";\n");
}

fn schema_json<T: schemars::JsonSchema>() -> Value {
    match serde_json::to_value(schema_for!(T)) {
        Ok(value) => value,
        Err(_) => Value::Object(Map::new()),
    }
}

fn schema_definitions(schema: &Value) -> Map<String, Value> {
    if let Some(defs) = schema.get("$defs").and_then(Value::as_object) {
        return defs.clone();
    }
    if let Some(defs) = schema.get("definitions").and_then(Value::as_object) {
        return defs.clone();
    }
    Map::new()
}

fn schema_to_valibot(
    schema: &Value,
    defs: &Map<String, Value>,
    known_names: &BTreeSet<String>,
    stack: &mut Vec<String>,
    brand: Option<&'static str>,
) -> String {
    if let Some(value) = schema.as_bool() {
        return if value {
            "v.unknown()".to_owned()
        } else {
            "v.never()".to_owned()
        };
    }

    let Some(object) = schema.as_object() else {
        return "v.unknown()".to_owned();
    };

    if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
        if let Some(name) = ref_name(reference) {
            if known_names.contains(name.as_str()) {
                return format!("{name}Schema");
            }
            if !stack.iter().any(|entry| entry == &name) {
                if let Some(def_schema) = defs.get(&name) {
                    stack.push(name.clone());
                    let rendered = schema_to_valibot(def_schema, defs, known_names, stack, None);
                    let _ = stack.pop();
                    return rendered;
                }
            }
        }
        return "v.unknown()".to_owned();
    }

    if let Some(constant) = object.get("const") {
        return format!("v.literal({})", js_value(constant));
    }

    if let Some(values) = object.get("enum").and_then(Value::as_array) {
        if values.len() == 1 {
            return format!("v.literal({})", js_value(&values[0]));
        }
        return format!("v.picklist([{}])", join_js_values(values));
    }

    if let Some(options) = schema_union_options(object) {
        if let Some(nullable_value_schema) = extract_nullable_union(options) {
            let wrapped = schema_to_valibot(nullable_value_schema, defs, known_names, stack, None);
            return format!("v.nullable({wrapped})");
        }
        let rendered = options
            .iter()
            .map(|item| schema_to_valibot(item, defs, known_names, stack, None))
            .collect::<Vec<_>>()
            .join(", ");
        return format!("v.union([{rendered}])");
    }

    if let Some(instance_type) = object.get("type") {
        if let Some(s) = instance_type.as_str() {
            return render_typed_schema(s, object, defs, known_names, stack, brand);
        }
        if let Some(types) = instance_type.as_array() {
            if let Some(nullable_value_schema) = extract_nullable_type_union(types, object) {
                let wrapped =
                    schema_to_valibot(&nullable_value_schema, defs, known_names, stack, brand);
                return format!("v.nullable({wrapped})");
            }
            let options = types
                .iter()
                .filter_map(Value::as_str)
                .map(|kind| {
                    let sub = json!({ "type": kind });
                    schema_to_valibot(&sub, defs, known_names, stack, None)
                })
                .collect::<Vec<_>>()
                .join(", ");
            return format!("v.union([{options}])");
        }
    }

    if object.get("properties").is_some() {
        return render_object_schema(object, defs, known_names, stack);
    }
    if object.get("items").is_some() {
        let items = object.get("items").unwrap_or(&Value::Null);
        let item_schema = schema_to_valibot(items, defs, known_names, stack, None);
        return format!("v.array({item_schema})");
    }

    "v.unknown()".to_owned()
}

fn render_typed_schema(
    kind: &str,
    object: &Map<String, Value>,
    defs: &Map<String, Value>,
    known_names: &BTreeSet<String>,
    stack: &mut Vec<String>,
    brand: Option<&'static str>,
) -> String {
    match kind {
        "string" => render_string_schema(object, brand),
        "boolean" => "v.boolean()".to_owned(),
        "number" | "integer" => "v.number()".to_owned(),
        "null" => "v.null()".to_owned(),
        "array" => {
            let items = object.get("items").unwrap_or(&Value::Null);
            let item_schema = schema_to_valibot(items, defs, known_names, stack, None);
            format!("v.array({item_schema})")
        }
        "object" => render_object_schema(object, defs, known_names, stack),
        _ => "v.unknown()".to_owned(),
    }
}

fn render_string_schema(object: &Map<String, Value>, brand: Option<&'static str>) -> String {
    let mut steps = vec!["v.string()".to_owned()];
    let min_length = object.get("minLength").and_then(Value::as_u64);
    let format = object.get("format").and_then(Value::as_str);

    if matches!(format, Some("uuid" | "email")) {
        steps.push("v.trim()".to_owned());
    }
    if matches!(format, Some("email")) {
        steps.push("v.toLowerCase()".to_owned());
        steps.push("v.email()".to_owned());
    }
    if matches!(format, Some("uuid")) {
        steps.push("v.uuid()".to_owned());
    }
    if let Some(value) = min_length {
        steps.push(format!("v.minLength({value})"));
    }
    if let Some(target_brand) = brand {
        steps.push(format!(
            "v.transform((value): Brand<string, \"{target_brand}\"> => value as Brand<string, \"{target_brand}\">)"
        ));
    }
    if steps.len() == 1 {
        return steps.pop().unwrap_or_else(|| "v.string()".to_owned());
    }
    format!("v.pipe({})", steps.join(", "))
}

fn render_object_schema(
    object: &Map<String, Value>,
    defs: &Map<String, Value>,
    known_names: &BTreeSet<String>,
    stack: &mut Vec<String>,
) -> String {
    let properties = object
        .get("properties")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    let required = object
        .get("required")
        .and_then(Value::as_array)
        .map(|entries| {
            entries
                .iter()
                .filter_map(Value::as_str)
                .map(ToOwned::to_owned)
                .collect::<HashSet<_>>()
        })
        .unwrap_or_default();

    let mut pairs = Vec::new();
    for (key, schema) in properties {
        let value_expr = schema_to_valibot(&schema, defs, known_names, stack, None);
        if required.contains(&key) {
            pairs.push(format!("  {key}: {value_expr},"));
        } else {
            pairs.push(format!("  {key}: v.optional({value_expr}),"));
        }
    }
    pairs.sort();
    if pairs.is_empty() {
        return "v.object({})".to_owned();
    }
    format!("v.object({{\n{}\n}})", pairs.join("\n"))
}

fn schema_union_options(object: &Map<String, Value>) -> Option<&Vec<Value>> {
    object
        .get("oneOf")
        .and_then(Value::as_array)
        .or_else(|| object.get("anyOf").and_then(Value::as_array))
        .or_else(|| object.get("allOf").and_then(Value::as_array))
}

fn extract_nullable_union(options: &[Value]) -> Option<&Value> {
    if options.len() != 2 {
        return None;
    }
    let left_is_null = is_null_schema(&options[0]);
    let right_is_null = is_null_schema(&options[1]);
    match (left_is_null, right_is_null) {
        (true, false) => Some(&options[1]),
        (false, true) => Some(&options[0]),
        _ => None,
    }
}

fn extract_nullable_type_union(types: &[Value], object: &Map<String, Value>) -> Option<Value> {
    if types.len() != 2 {
        return None;
    }
    let kinds = types
        .iter()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    if !kinds.contains("null") || kinds.len() != 2 {
        return None;
    }
    let non_null = kinds
        .into_iter()
        .find(|kind| *kind != "null")
        .unwrap_or("string");
    let mut clone = object.clone();
    clone.insert("type".to_owned(), Value::String(non_null.to_owned()));
    Some(Value::Object(clone))
}

fn is_null_schema(schema: &Value) -> bool {
    let Some(object) = schema.as_object() else {
        return false;
    };
    object.get("type").and_then(Value::as_str) == Some("null")
}

fn ref_name(reference: &str) -> Option<String> {
    let prefix_defs = "#/$defs/";
    let prefix_legacy = "#/definitions/";
    if let Some(value) = reference.strip_prefix(prefix_defs) {
        return Some(value.to_owned());
    }
    reference.strip_prefix(prefix_legacy).map(ToOwned::to_owned)
}

fn js_value(value: &Value) -> String {
    match serde_json::to_string(value) {
        Ok(serialized) => serialized,
        Err(_) => "null".to_owned(),
    }
}

fn join_js_values(values: &[Value]) -> String {
    values.iter().map(js_value).collect::<Vec<_>>().join(", ")
}
