//! `xtask generate-web-contracts` — emit canonical web account contract
//! types from Rust contract sources.

use anyhow::{Context, Result};
use std::fmt::Write as _;
use std::fs;
use std::io::Write;
use std::path::Path;
use tanren_contract::AccountFailureReason;

const OUTPUT_PATH: &str = "apps/web/src/app/lib/generated/account-contract.ts";

pub(crate) fn run(root: &Path) -> Result<()> {
    let output = root.join(OUTPUT_PATH);
    let parent = output
        .parent()
        .context("generated web contract path has no parent")?;
    fs::create_dir_all(parent)
        .with_context(|| format!("create generated dir {}", parent.display()))?;

    let contents = render_contract_file();
    fs::write(&output, contents).with_context(|| format!("write {}", output.display()))?;

    let stdout = std::io::stdout();
    let mut handle = stdout.lock();
    let _ = writeln!(handle, "generate-web-contracts: wrote {}", output.display());
    Ok(())
}

fn render_contract_file() -> String {
    let mut rendered = String::new();
    rendered
        .push_str("// Generated by `cargo run -q -p tanren-xtask -- generate-web-contracts`.\n");
    rendered.push_str(
        "// Source of truth: `tanren-contract` account wire shapes and failure taxonomy.\n\n",
    );
    rendered.push_str("export type Brand<TValue, TBrand extends string> = TValue & {\n");
    rendered.push_str("  readonly __brand: TBrand;\n");
    rendered.push_str("};\n\n");
    rendered.push_str("export type AccountId = Brand<string, \"AccountId\">;\n");
    rendered.push_str("export type OrgId = Brand<string, \"OrgId\">;\n");
    rendered.push_str("export type Identifier = string;\n\n");
    rendered
        .push_str("export const asAccountId = (value: string): AccountId => value as AccountId;\n");
    rendered.push_str("export const asOrgId = (value: string): OrgId => value as OrgId;\n\n");
    rendered.push_str("export interface AccountView {\n");
    rendered.push_str("  id: AccountId;\n");
    rendered.push_str("  identifier: Identifier;\n");
    rendered.push_str("  display_name: string;\n");
    rendered.push_str("  org: OrgId | null;\n");
    rendered.push_str("}\n\n");
    rendered.push_str("export interface ActiveAccountView {\n");
    rendered.push_str("  id: AccountId;\n");
    rendered.push_str("  display_name: string;\n");
    rendered.push_str("  org: OrgId | null;\n");
    rendered.push_str("}\n\n");
    rendered.push_str("export interface SignedInAccountView {\n");
    rendered.push_str("  account: ActiveAccountView;\n");
    rendered.push_str("  is_active: boolean;\n");
    rendered.push_str("}\n\n");
    rendered.push_str("export type ListActiveAccountsRequest = Record<never, never>;\n\n");
    rendered.push_str("export interface ListActiveAccountsResponse {\n");
    rendered.push_str("  accounts: SignedInAccountView[];\n");
    rendered.push_str("}\n\n");
    rendered.push_str("export interface SwitchActiveAccountRequest {\n");
    rendered.push_str("  target_account_id: AccountId;\n");
    rendered.push_str("}\n\n");
    rendered.push_str("export interface SwitchActiveAccountResponse {\n");
    rendered.push_str("  active_account_id: AccountId;\n");
    rendered.push_str("  accounts: SignedInAccountView[];\n");
    rendered.push_str("}\n\n");
    rendered.push_str("export type AccountFailureCode =\n");
    for reason in AccountFailureReason::all() {
        let _ = writeln!(rendered, "  | \"{}\"", reason.code());
    }
    rendered.push_str(";\n");
    rendered
}
