//! Install manifest and project-uninstall wire shapes.
//!
//! These types define the v1 install manifest format and the
//! preview/apply contract for removing Tanren-generated assets from a
//! repository. Every interface (CLI, API, MCP, TUI) resolves to the
//! same shapes — keeping them here is the architectural guarantee that
//! the surfaces stay equivalent.

use chrono::{DateTime, Utc};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Default relative path for the v1 install manifest inside a repo.
pub const MANIFEST_V1_PATH: &str = ".tanren/install-manifest.json";

/// Current manifest schema version.
pub const MANIFEST_V1_VERSION: u32 = 1;

/// Ownership classification for a file tracked by the install manifest.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum FileOwnership {
    /// Generated by Tanren — eligible for removal when unchanged.
    TanrenGenerated,
    /// User-created or user-edited — never removed by uninstall.
    UserOwned,
}

/// A single file entry in the install manifest.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, ToSchema)]
pub struct ManifestEntry {
    /// Relative path from the repository root (forward-slash separated).
    pub path: String,
    /// Who owns this file.
    pub ownership: FileOwnership,
    /// SHA-256 hex digest of the file content at install time.
    pub content_hash: String,
    /// When the file was generated.
    pub generated_at: DateTime<Utc>,
}

/// The v1 install manifest persisted at [`MANIFEST_V1_PATH`].
///
/// The manifest records every Tanren-managed file in the repository at
/// install time so that uninstall can distinguish generated assets
/// (safe to remove when unchanged) from user-owned work (never
/// removed).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, ToSchema)]
pub struct InstallManifest {
    /// Manifest schema version (always [`MANIFEST_V1_VERSION`]).
    pub version: u32,
    /// File entries tracked by this installation.
    pub entries: Vec<ManifestEntry>,
    /// When the manifest was created.
    pub created_at: DateTime<Utc>,
}

/// Preview of a repo uninstall — shows what will be removed and what
/// will be preserved, without performing any deletion.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, ToSchema)]
pub struct UninstallPreview {
    /// Files that will be removed (unchanged Tanren-generated assets).
    pub to_remove: Vec<String>,
    /// Files that will be preserved (user-owned or modified).
    pub preserved: Vec<PreservedFile>,
    /// Relative path to the manifest file (also removed on apply).
    pub manifest_path: String,
}

/// A file that will be preserved during uninstall, with reason.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, ToSchema)]
pub struct PreservedFile {
    /// Relative path from the repository root.
    pub path: String,
    /// Why this file is preserved.
    pub reason: PreserveReason,
}

/// Why a file is preserved during uninstall.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum PreserveReason {
    /// File is user-owned — never removed by uninstall.
    UserOwned,
    /// File was Tanren-generated but has been edited since install.
    ModifiedSinceInstall,
    /// File was Tanren-generated but is already absent from disk.
    AlreadyRemoved,
}

/// Request to preview which Tanren-generated assets would be removed.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, ToSchema)]
pub struct UninstallPreviewRequest {
    /// Absolute or relative path to the local repository root.
    pub repo_path: String,
}

/// Request to apply an uninstall operation.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, ToSchema)]
pub struct UninstallApplyRequest {
    /// Absolute or relative path to the local repository root.
    pub repo_path: String,
    /// Must be `true` to confirm the destructive operation.
    pub confirm: bool,
}

/// Result of applying an uninstall.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, ToSchema)]
pub struct UninstallResult {
    /// Files that were actually removed.
    pub removed: Vec<String>,
    /// Files that were preserved.
    pub preserved: Vec<PreservedFile>,
    /// Whether the manifest file itself was removed.
    pub manifest_removed: bool,
}
